#https://docs.ansible.com/ansible/latest/collections/netapp/ontap/index.html#plugins-in-netapp-ontap
---
- hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true  # Stop playbook execution if any task fails

  collections:
    - netapp.ontap

  vars:
    sub_task1: "06_Display_volume_snapshot_information_rest_tasks1.yml"
    sub_task2: "06_Display_volume_snapshot_information_rest_tasks2.yml"
    output_f_name: "06_Display_volume_snapshot_information_rest_tasks"
  vars_files:
    - vars.yml

  tasks:

    # Ensure the 'json' directory exists
    - name: Ensure the 'json' directory exists
      file:
        path: json
        state: directory
        mode: '0755'

    # Ensure absence of old freeze files
    - name: Ensure absence of old freeze files
      file:
        path: "json/{{ output_f_name }}_*.json"
        state: absent

    # Iterate over storages and run tasks
    - name: Gather SVM information
      include_tasks: "{{ sub_task1 }}"
      loop: "{{ storages }}"
      loop_control:
        loop_var: storage
      when: storage.enabled

