#ansible-playbook 08_Display_volume_information_rest.yml --extra-vars "storageip=192.168.56.4"
#ansible-playbook 08_Display_volume_information_rest.yml --extra-vars "storageip=10.199.14.180"
#ansible-playbook 08_Display_volume_information_rest.yml --extra-vars "storageip=10.199.14.170"
---
- hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true  # Stop playbook execution if any task fails

  collections:
    - netapp.ontap
  vars_files:
    - vars.yml
  vars:
    login: &login
      hostname: "{{ login.hostname }}"
      username: "{{ login.username }}"
      password: "{{ login.password }}"
      https: "{{ login.https }}"
      validate_certs: "{{ login.validate_certs }}"
    svms: "{{ svms }}"
    output_file: "json/Display_volume_information_rest.json"  # Define the output file
    output_file2: "{{ output_file }}2"  # Define the output file
    output_file3: "{{ output_file }}3"  # Define the output file

  tasks:

    # Ensure absence of old freeze files
    - name: Ensure absence of old freeze files
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - "{{ output_file }}"
        - "{{ output_file }}2"
        - "{{ output_file }}3"

    - name: run ONTAP gather facts for storage/volumes (Selected fields)
      netapp.ontap.na_ontap_rest_info:
        use_rest: always
        gather_subset:
          - storage/volumes
        fields:
          - 'name'
          - 'uuid'
          - 'state'
          - 'type'
          - 'style'
          - 'size'
          - 'comment'
          - 'create_time'
          - 'language'
          - 'snapshot_policy.name'  # Nested field
          - 'nas.export_policy.name' # Nested field
          - 'svm.name'  # Nested field
          - 'svm.uuid'  # Nested field
          - 'clone.is_flexclone'  # Nested field
          - 'snapmirror.is_protected'  # Nested field
          - 'aggregates.name'  # Nested field
          - 'aggregates.uuid'  # Nested field
          - 'snapshot-count'
        <<: *login
      register: storage_volumes_info_selected_fields

    - name: Output selected information for volume in JSON format
      copy:
        content: "{{ storage_volumes_info_selected_fields  | to_json }}"
        dest: "{{ output_file }}"

    - name: run ONTAP gather facts2 for storage/volumes
      netapp.ontap.na_ontap_rest_cli:
        command: 'volume'
        verb: 'GET'
        params:
          fields: "volume,junction-path,activity-tracking-unsupported-reason"
        <<: *login
      register:  storage_volumes_info2

    - name: Write lun_mapping information to JSON file
      copy:
        content: "{{ storage_volumes_info2 | to_json }}"
        dest: "{{ output_file2 }}"

    - name: run ONTAP gather facts3 for storage/volumes
      netapp.ontap.na_ontap_rest_cli:
        command: 'cifs/share'
        verb: 'GET'
        params:
          fields: "volume,share-name,cifs-server,path,vserver"
        <<: *login
      register:  storage_volumes_info3

    - name: Write lun_mapping information to JSON file
      copy:
        content: "{{ storage_volumes_info3 | to_json }}"
        dest: "{{ output_file3 }}"
