#ansible-playbook 08_Display_volume_information_rest.yml --extra-vars "storageip=192.168.56.4"
#ansible-playbook 08_Display_volume_information_rest.yml --extra-vars "storageip=10.199.14.180"
#ansible-playbook 08_Display_volume_information_rest.yml --extra-vars "storageip=10.199.14.170"
---
- hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true  # Stop playbook execution if any task fails

  collections:
    - netapp.ontap
  vars_files:
    - vars.yml
  vars:
    login: &login
      hostname: "{{ login.hostname }}"
      username: "{{ login.username }}"
      password: "{{ login.password }}"
      https: "{{ login.https }}"
      validate_certs: "{{ login.validate_certs }}"
    svms: "{{ svms }}"
    output_file: "json/Display_volume_information_rest.json"  # Define the output file

  tasks:

    # Ensure absence of old freeze files
    - name: Ensure absence of old freeze files
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - "{{ output_file }}"

    - name: run ONTAP gather facts for storage/volumes (Selected fields)
      netapp.ontap.na_ontap_rest_cli:
        command: 'volume'
        verb: 'GET'
        params:
          fields: "volume,state,type,volume-style,size,comment,create-time,language,snapshot-policy,junction-path,clone-volume,activity-tracking-unsupported-reason,create-time,vserver,aggregate"
        <<: *login
      register:  storage_volumes_info

    - name: Write lun_mapping information to JSON file
      copy:
        content: "{{ storage_volumes_info | to_json }}"
        dest: "{{ output_file }}"

