#ansible-playbook 10_job_schedule_cron_info_rest.yml --extra-vars "storageip=192.168.56.4"
#ansible-playbook 10_job_schedule_cron_info_rest.yml --extra-vars "storageip=10.199.14.180"
#ansible-playbook 10_job_schedule_cron_info_rest.yml --extra-vars "storageip=10.199.14.170"
---
- hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true  # Stop playbook execution if any task fails

  collections:
    - netapp.ontap
  vars_files:
    - vars.yml
  vars:
    login: &login
      hostname: "{{ login.hostname }}"
      username: "{{ login.username }}"
      password: "{{ login.password }}"
      https: "{{ login.https }}"
      validate_certs: "{{ login.validate_certs }}"
    svms: "{{ svms }}"
    output_file2: "json/Display_job_schedule_cron_info_extra_rest.json"  # Define the output file
  tasks:
    # Ensure absence of old freeze files
    - name: Ensure absence of old freeze files
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - "{{ output_file2 }}"

    - name: Retrieve extra information for job schedule information
      netapp.ontap.na_ontap_rest_cli:
        command: 'job/schedule'
        verb: 'GET'
        params:
          fields: "type,description,name,cluster"
        <<: *login
      register: job_schedule_info_extra

    - name: Write extra schedule information of specified volume into "{{ output_file2 }}" JSON file
      copy:
        content: "{{ job_schedule_info_extra| to_json }}"
        dest: "{{ output_file2 }}"

