#https://docs.ansible.com/ansible/latest/collections/netapp/ontap/index.html#plugins-in-netapp-ontap
#ansible-playbook 04_Display_ontap_node_info_rest.yml --extra-vars "storageip=192.168.56.4"
#ansible-playbook 04_Display_ontap_node_info_rest.yml --extra-vars "storageip=10.199.14.180"
#ansible-playbook 04_Display_ontap_node_info_rest.yml --extra-vars "storageip=10.199.14.170"
---
- hosts: localhost 
  connection: local
  gather_facts: false
  any_errors_fatal: true  # Stop playbook execution if any task fails

  collections:
    - netapp.ontap
  vars_files:
    - vars.yml
  vars:
    login: &login 
      hostname: "{{ login.hostname }}"
      username: "{{ login.username }}"
      password: "{{ login.password }}"
      https: "{{ login.https }}"
      validate_certs: "{{ login.validate_certs }}"
    svms: "{{ svms }}"
    output_file: "json/Display_ontap_node_info_rest.json"  # Define the output file
    output_file1: "json/Display_ontap_node_info_rest.json1"  # Define the output file
    output_file2: "json/Display_ontap_node_info_rest.json2"  # Define the output file

  tasks:

    # Ensure absence of old freeze files
    - name: Ensure absence of old freeze files
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - "{{ output_file }}"

    - name: show igroup
      netapp.ontap.na_ontap_rest_cli:
        command: 'igroup'
        verb: 'GET'
        params:
          vserver: "svm-iscsi-r"
          igroup: "SVR040202"
        <<: *login
      register:  lun_mapping

    - name: Write lun_mapping information to JSON file
      copy:
        content: "{{ lun_mapping | to_json }}"
        dest: "{{ output_file }}"
