#https://docs.ansible.com/ansible/latest/collections/netapp/ontap/na_ontap_rest_info_module.html
#ansible-playbook 09_Display_volume_snapshot_information_rest.yml --extra-vars "volume=<your_volume_name> svm=<your_svm_name>"
#ansible-playbook 09_Display_volume_snapshot_information_rest.yml --extra-vars "volume=vs2_root svm=vs2 storageip=192.168.178.4 output_file1=json/Display_volume_snapshot_info1_rest.json output_file2=json/Display_volume_snapshot_info2_rest.json"
#ansible-playbook 09_Display_volume_snapshot_information_rest.yml --extra-vars "volume=vs2_root svm=vs2 storageip=10.199.14.170"
#ansible-playbook 09_Display_volume_snapshot_information_rest.yml --extra-vars "volume=vs2_root svm=vs2 storageip=10.199.14.180"
---
- hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true  # Stop playbook execution if any task fails

  collections:
    - netapp.ontap
  vars_files:
    - vars.yml
  vars:
    login: &login
      hostname: "{{ login.hostname }}"
      username: "{{ login.username }}"
      password: "{{ login.password }}"
      https: "{{ login.https }}"
      validate_certs: "{{ login.validate_certs }}"
    #svm: svm01_nfs
    #volume: svm01_nfs_datavol
    #output_file1: "json/Display_volume_snapshot_info1_rest.json"  # Define the output file
    #output_file2: "json/Display_volume_snapshot_info2_rest.json"  # Define the output file
  tasks:

    # Ensure absence of old freeze files
    - name: Ensure absence of old freeze files
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - "{{ output_file1 }}"
        - "{{ output_file2 }}"

    - name: Retrieve snapshot information of specified svm and volume with rest_info
      netapp.ontap.na_ontap_rest_info:
        use_rest: always
        gather_subset:
          - storage/volumes/snapshots
        owning_resource:
           volume_name: "{{ volume }}"
           svm_name:  "{{ svm }}"
        <<: *login
      register: storage_volumes_snapshot_info_selected_fields

    - name: Write snapshot information of specified svm and volume in "{{ output_file1 }}" JSON format
      copy:
        content: "{{ storage_volumes_snapshot_info_selected_fields  | to_json }}"
        dest: "{{ output_file1 }}"

    - name: Retrieve extra snapshot information of specified volume with rest_cli
      netapp.ontap.na_ontap_rest_cli:
        command: 'snapshot'
        verb: 'GET'
        params:
          vserver: "{{ svm }}"
          volume: "{{ volume }}"
          fields: "create-time,snapmirror-label"
        <<: *login
      register: all_volume_snapshot_info

    - name: Write extra snapshot information of specified volume into "{{ output_file2 }}" JSON file
      copy:
        content: "{{  all_volume_snapshot_info| to_json }}"
        dest: "{{ output_file2 }}"
